spring:
  application:
    name: phoibe-doc-cms
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    resources:
      chain:
        gzipped: true
        cache: false
    cache-period: 604800
  redis:
    host: 10.10.40.28
    port: 9990
    database: 1
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@101.201.220.162:1522:wemem
    username: docsysadmin
    password: Yhc5880908
    hikari:
      maxLifetime: 1765000
      maximumPoolSize: 15
  http:
    multipart:
      maxFileSize: 1048580000Mb
      maxRequestSize: 10485800000MB
  cache:
    ehcache:
      config: ehcache.xml
  aop:
    auto: true # Add @EnableAspectJAutoProxy.
    proxy-target-class: false # Whether subclass-based (CGLIB) proxies are to be created (true) as opposed to standard Java interface-based proxies (false).
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
server:
  port: 8090
  tomcat:
    max-threads: 1000
    uri-encoding: UTF-8
mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  typeAliasesPackage: com.apus.balance.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jasypt:
  encryptor:
    password: foo
crosDomain: '*'

logfile: D:/JavaTool/satic/log
exportlog: D:/JavaTool/satic/exportlog
#window:status:1
#linux: status:2

breakpoint:
  upload:
    window: D:/JavaTool/satic/docword/
    linux: satic/docword/
    status: 1
    chunkSize: 5242880