$(function(){});function isNullOrUndefinedOrEmpty(_value){if(_value==undefined||_value==null||_value==''){return true;}
else{return false;}}
function Scrool(){this.scrollBoxHeight='';this.scrollContHeight='';this.scrollTiaoHheight='';this.contMaxjuli='';this.scrollHuakuaiHeight='';this.huakuaiMaxjuli='';}
$.fn.extend({customScrollbar:function(initTop,huakuaiColor){$(this).each(function(){var self=$(this);var strCont="";strCont='<div class="scroll_tiao">'
        +'<div class="scroll_huakuai"></div>';self.find('.scroll_box').append(strCont);self.find('.scroll_box').find('.scroll_tiao').css({'height':'100%','position':'absolute','background-color':'#ccc','width':'16px','right':'0','top':'0'});self.find('.scroll_box').find('.scroll_cont').css({'position':'absolute','top':'0','left':'0','margin-right':'20px'});self.find('.scroll_box').find('.scroll_huakuai').css({"width":"13px","height":'40px',"z-index":"999","margin-left":"1px","position":"absolute","right":"1px"});var scrool=new Scrool();scrool.scrollBoxHeight=self.height();scrool.scrollContHeight=self.find('.scroll_cont').height();scrool.scrollTiaoHheight=scrool.scrollBoxHeight;scrool.contMaxjuli=scrool.scrollContHeight-scrool.scrollBoxHeight;scrool.scrollHuakuaiHeight=self.find('.scroll_huakuai').height();scrool.huakuaiMaxjuli=scrool.scrollTiaoHheight-scrool.scrollHuakuaiHeight;if(isNullOrUndefinedOrEmpty(initTop)){initTop=0;}else if(initTop.indexOf('px')>0){var initTop1=parseInt(initTop);if(initTop1>scrool.huakuaiMaxjuli){throw '您传入的第一个参数不正确，不能大于滑块能滚动的最大高度';return false;}}else if(initTop.indexOf('%')>0){var initTop2=parseInt(initTop);var percent_top=(scrool.huakuaiMaxjuli/scrool.scrollTiaoHheight)*100;if(initTop2>percent_top){throw '您传入的第一个参数不正确，不能大于滑块能滚动的最大高度%';}}
        if(isNullOrUndefinedOrEmpty(huakuaiColor)){huakuaiColor='red';}
        self.find('.scroll_box').find('.scroll_huakuai').css({'top':initTop,'background-color':huakuaiColor});var huakuaiTop=parseInt(self.find('.scroll_box').find('.scroll_huakuai').css('top'));var scroll_contTop=-(scrool.contMaxjuli*(huakuaiTop/scrool.huakuaiMaxjuli));self.find('.scroll_box').find('.scroll_huakuai').css({"top":huakuaiTop+'px'});self.find('.scroll_box').find('.scroll_cont').css({"top":scroll_contTop+'px'});if(scrool.scrollContHeight<=scrool.scrollBoxHeight){self.find('.scroll_box').find('.scroll_tiao').hide();}else{self.find('.scroll_box').find('.scroll_tiao').show();function wheel(){self.find('.scroll_box').bind('mousewheel DOMMouseScroll',function(e){e.preventDefault();var _delta=parseInt(e.originalEvent.wheelDelta||-e.originalEvent.detail);var huakuaiTop=parseInt(self.find('.scroll_box').find('.scroll_huakuai').css('top'));var scroll_contTop=0;if(_delta>0){huakuaiTop-=10;scroll_contTop=-(scrool.contMaxjuli*(huakuaiTop/scrool.huakuaiMaxjuli));if(huakuaiTop<0){self.find('.scroll_box').find('.scroll_huakuai').css({"top":0+'px'});self.find('.scroll_box').find('.scroll_cont').css({"top":0+'px'});return false;}
            self.find('.scroll_box').find('.scroll_huakuai').css({"top":huakuaiTop+'px'});self.find('.scroll_box').find('.scroll_cont').css({"top":scroll_contTop+'px'});return false;}else{huakuaiTop+=10;scroll_contTop=-(scrool.contMaxjuli*(huakuaiTop/scrool.huakuaiMaxjuli));if(huakuaiTop>scrool.huakuaiMaxjuli){self.find('.scroll_box').find('.scroll_huakuai').css({"top":scrool.huakuaiMaxjuli+'px'});self.find('.scroll_box').find('.scroll_cont').css({"top":-scrool.contMaxjuli+'px'});return false;}
            self.find('.scroll_box').find('.scroll_huakuai').css({"top":huakuaiTop+'px'});self.find('.scroll_box').find('.scroll_cont').css({"top":scroll_contTop+'px'});return false;}
            return false;});}
            function drag(){self.find('.scroll_box').find('.scroll_huakuai').bind('mousedown',function(event){if(event.button==0){obj_offsetTop=self.find('.scroll_huakuai').offset().top;gapY=event.clientY-self.find('.scroll_huakuai').offset().top;self.find('.scroll_box').bind('mousemove',move);$(document).bind('mouseup',stop)
                function move(e1){var box_margin_top=parseInt(self.find('.scroll_box').offset().top);var huakuaiTop=e1.clientY-gapY-box_margin_top;var scroll_contTop=-(scrool.contMaxjuli*(huakuaiTop/scrool.huakuaiMaxjuli));if(huakuaiTop<0){huakuaiTop=0;scroll_contTop=0;}else if(huakuaiTop>scrool.huakuaiMaxjuli){huakuaiTop=scrool.huakuaiMaxjuli;scroll_contTop=-scrool.contMaxjuli;}
                    self.find('.scroll_huakuai').css({"top":huakuaiTop+'px'});self.find('.scroll_cont').css({"top":scroll_contTop+'px'});}
                function stop(){self.find('.scroll_box').unbind('mousemove',move);self.find('.scroll_box').find('.scroll_huakuai').unbind("mouseup",stop);}}
                event.preventDefault();});}
            wheel();drag();}});}});